### ISSUE TITLE
Status is not correct and updating after formating

### ISSUE THREAD

**Issue by touseef30** [hammad11ali/OraclePLSQLUnwrapper#2]
After formatting, in the status bar, the status is "Unwrapping" which should be "Formating", and after the process finished the status didn't update as shown in the attached image.
![image](https://user-images.githubusercontent.com/46575326/168533065-4e3a4bc9-398d-479f-9425-06887bd7fa74.png)

**Comment by hammad11ali** [comment]
The bug has been fixed in version 0.0.5
