### ISSUE TITLE
Issue when format using short key without selecting all text

### ISSUE THREAD

**Issue by touseef30** [hammad11ali/OraclePLSQLUnwrapper#3]
When a user didn't select all the text and use the short key for formating while placing the cursor at a random space in code, the text "CREATE OR REPLACE" printed into the code.
![image](https://user-images.githubusercontent.com/46575326/168541014-950854fe-d146-47de-b279-d3405329706c.png)

**Comment by hammad11ali** [comment]
Create or replace will no longer be added when formatting using the shortcut key. For now, we need to select all before performing unwrap or formatting. This will be fixed in the next patch
